---
title: "Wind in the Willows Analysis"
author: "Shelby Walsh"
date: "2/21/2021"
output: html_document
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(textdata)
library(pdftools)
library(ggwordcloud)
```

# Wind in the Willows: The cheekiest book ever

https://freeditorial.com/en/books/the-wind-in-the-willows/related-books

```{r, cache = TRUE}
willow_text <- pdf_text("ww.pdf")

willow_tidy <- data.frame(willow_text) %>% 
  mutate(text_full = str_split(willow_text, pattern = '\\n')) %>% 
  unnest(text_full) %>% 
  mutate(text_full = str_trim(text_full)) 
```


```{r}
willow_df <- willow_tidy %>% 
  slice(-(1:4))
  

willow_tokens <- willow_df %>% 
  unnest_tokens(word, text_full) %>% 
  select(-willow_text)

willow_nonstop_words <- willow_tokens %>% 
  anti_join(stop_words)

nonstop_counts <- willow_nonstop_words %>% 
  count(word)

top_200 <- nonstop_counts %>% 
  arrange(-n) %>% 
  slice(1:200)

top_100_wo <- nonstop_counts %>% 
  arrange(-n) %>% 
  slice(1:100) %>% 
  slice(-(1:4))

top_5_words <- nonstop_counts %>% 
  arrange(-n) %>% 
  slice(1:5)

```


```{r}
ww_cloud <- ggplot(data = top_100_wo, aes(label = word)) +
  geom_text_wordcloud(aes(color = n, size = n), shape = "diamond") +
  scale_size_area(max_size = 6) +
  scale_color_gradientn(colors = c("darkgreen","blue","purple")) +
  theme_minimal()

ww_cloud
```

```{r}
get_sentiments(lexicon = "nrc")

get_sentiments(lexicon = "afinn")

afinn_pos <- get_sentiments("afinn") %>% 
  filter(value %in% c(3,4,5))

afinn_pos

willow_afinn <- willow_nonstop_words %>% 
  inner_join(get_sentiments("afinn"))

willow_afinn_count <- willow_afinn %>% 
  count(word)


willow_nrc <- willow_nonstop_words %>% 
  inner_join(get_sentiments("nrc"))

willow_nrc_counts <- willow_nrc %>% 
  count(sentiment)

ggplot(data = willow_nrc_counts, aes(x = sentiment, y = n)) +
  geom_col() +
  coord_flip()
```


